# Generated by Django 4.1.5 on 2023-01-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.culture'),
        ),
        migrations.AddField(
            model_name='field',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.farmer'),
        ),
        migrations.AddField(
            model_name='field',
            name='seasons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmapp.season'),
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
